package com.smart_ecomernce_api.smart_ecomernce_api.validator;

import com.smart_ecomernce_api.smart_ecomernce_api.modules.product.entity.Product;
import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;

public class PriceRangeValidator implements ConstraintValidator<ValidPriceRange, Product> {

    @Override
    public void initialize(ValidPriceRange annotation) {
        ConstraintValidator.super.initialize(annotation);
    }

    @Override
    public boolean isValid(Product value, ConstraintValidatorContext context) {
        // Use actual Product getter names generated by Lombok: getDiscountPrice()
        if (value == null || value.getPrice() == null || value.getDiscountPrice() == null) {
            return true; // Let @NotNull handle null validation
        }

        // Discounted price should always be less than or equal to original price
        boolean isValid = value.getDiscountPrice().compareTo(value.getPrice()) <= 0;

        if (!isValid) {
            context.disableDefaultConstraintViolation();
            context.buildConstraintViolationWithTemplate(
                    "Discounted price (" + value.getDiscountPrice() +
                            ") must be less than or equal to original price (" + value.getPrice() + ")")
                    .addConstraintViolation();
        }

        return isValid;
    }
}